/* Generated By:JavaCC: Do not edit this line. MeinParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MeinParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHILE = 5;
  /** RegularExpression Id. */
  int DO = 6;
  /** RegularExpression Id. */
  int BEGIN = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int IN = 9;
  /** RegularExpression Id. */
  int OUT = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int ZERO = 12;
  /** RegularExpression Id. */
  int EINS = 13;
  /** RegularExpression Id. */
  int IDENT = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int NOTEQUAL = 17;
  /** RegularExpression Id. */
  int KOMMA = 18;
  /** RegularExpression Id. */
  int LRUNDKLAMMER = 19;
  /** RegularExpression Id. */
  int RRUNDKLAMMER = 20;
  /** RegularExpression Id. */
  int SEMIKOLEN = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"while\"",
    "\"do\"",
    "\"begin\"",
    "\"end\"",
    "\"in\"",
    "\"out\"",
    "\"var\"",
    "\"0\"",
    "\"1\"",
    "<IDENT>",
    "\"=\"",
    "\"+\"",
    "\"!=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\";\"",
  };

}
